// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtjJa04XAnFnttjrzA6oSQiN8PQQV69qE',
    appId: '1:915254355155:web:b696b5a7ca4b47d593e026',
    messagingSenderId: '915254355155',
    projectId: 'my-tradebook',
    authDomain: 'my-tradebook.firebaseapp.com',
    storageBucket: 'my-tradebook.appspot.com',
    measurementId: 'G-HBZ9PXZ5QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm458xHP4s-sS74QwzZGNyOlOMhwxyu5k',
    appId: '1:915254355155:android:e2f71d8341c161a193e026',
    messagingSenderId: '915254355155',
    projectId: 'my-tradebook',
    storageBucket: 'my-tradebook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB28yA3DdhAbPBoCA8ghQrIWnTbVmcPfM',
    appId: '1:915254355155:ios:27aa08fc2eca392993e026',
    messagingSenderId: '915254355155',
    projectId: 'my-tradebook',
    storageBucket: 'my-tradebook.appspot.com',
    iosClientId: '915254355155-lrv5vhiqiihdqv0o9nb2m7e29cqoolk6.apps.googleusercontent.com',
    iosBundleId: 'com.vineethkolichal.myTradebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB28yA3DdhAbPBoCA8ghQrIWnTbVmcPfM',
    appId: '1:915254355155:ios:27aa08fc2eca392993e026',
    messagingSenderId: '915254355155',
    projectId: 'my-tradebook',
    storageBucket: 'my-tradebook.appspot.com',
    iosClientId: '915254355155-lrv5vhiqiihdqv0o9nb2m7e29cqoolk6.apps.googleusercontent.com',
    iosBundleId: 'com.vineethkolichal.myTradebook',
  );
}
